from os import getenv


BOT_TOKEN = getenv("BOT_TOKEN")

FAQ_LINK = getenv("FAQ_LINK") or "https://t.me"
SUPPORT_BOT_LINK = getenv("SUPPORT_BOT_LINK") or "https://t.me"

_API_SERVICE_NAME = getenv("API_SERVICE_NAME")
_API_SERVICE_PORT = getenv("API_SERVICE_PORT")

API_ENDPOINT = f"http://{_API_SERVICE_NAME}:{_API_SERVICE_PORT}/api/v1"

PERCENTAGE_OF_REFERRALS = 15

WEEK_SUBSCRIPTION_COST = 50
ONE_MONTH_SUBSCRIPTION_COST = 150
THREE_MONTHS_SUBSCRIPTION_COST = 300
SIX_MONTHS_SUBSCRIPTION_COST = 500
YEAR_SUBSCRIPTION_COST = 800
